baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'paper'

[taxonomies]
  tag = 'tags'
  mood = 'moods'

[menus]
  [[menus.main]]
    name = 'hôm'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'về tớ'
    pageRef = '/about/'
    weight = 20

  [[menus.main]]
    name = 'suy nghĩ'
    pageRef = '/suy-nghi/'
    weight = 21

  [[menus.main]]
    name = 'nốt cuối ngày'
    pageRef = '/not-cuoi-ngay/'
    weight = 22

  [[menus.main]]
    name = 'chủ đề'
    pageRef = '/tags/'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
